### ISSUE TITLE
Opal version pin

### ISSUE THREAD

**Issue by wied03** [zetachang/opalrb-loader#5]
I like the progress with tests here.

Would you consider a PR that either?

A) Removes the opal compiler from this distro

or

B) Keeps it in there, but allows you to override the compiler with a user provided one?

Having to update this package every time the compiler changes for a release (which is often) might be a lot of work.

**Comment by cj** [comment]
My vote is for `B` :)

**Comment by zetachang** [comment]
Same for B here.

CJ Lazell notifications@github.com 於 2016年4月7日週四 上午2:53 寫道：

**Comment by wied03** [comment]
FYI, I'm going to plan on doing work on CJ's fork from now on.

**Comment by zetachang** [comment]
Totally fine with it and glad to see the project move on, feel free to ping me if any help is needed. :smiley:

**Comment by wied03** [comment]
@zetachang - Thanks for the work you put into this.
